version: '3.8'

services:
  db_dengue:
    image: mysql:8.0
    container_name: mysql_dengue
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dengue_db
      MYSQL_USER: dengue_user
      MYSQL_PASSWORD: dengue_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: